config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'top#index'

  resources :articles do
    resources :comments, only: [:create]
    collection do
      get 'search'
      get 'cook'
      get 'clean'
      get 'beauty'
      get 'other'
      get 'rank'
    end
  end

  resources :users, only: [:show] 
  resources :mylikes, only: [:show]
  
  post '/articles/:article_id/likes' => "likes#create"
  delete '/articles/:article_id/likes' => "likes#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  mount_uploader :image, ImageUploader

  enum category: { Cook: 1, Beauty: 2, Clean: 3, Other: 4 }, _prefix: true

  validates :title, presence: true
  validates :text, presence: true
  validates :image, presence: true
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nickname, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: "フォーマットが不適切です"}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    articles_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show, :search, :cook, :beauty, :clean, :other]
  before_action :page_article, only: [:index, :cook, :beauty, :clean, :other]

  def index
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    if @article.save
      redirect_to articles_path
    else
      render action: :new
    end
  end

  def show 
    @comments = @article.comments.includes(:user)
  end

  def destroy
    if @article.user_id == current_user.id
      @article.destroy
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      redirect_to edit_article_path
    end
  end

  def cook
  end

  def beauty
  end

  def clean
  end

  def other
  end

  def rank
    @articles = Article.includes(:user).page(params[:page]).per(6).order("likes_count DESC")
  end


  def search
    @articles = Article.where('title LIKE(?)', "%#{params[:keyword]}%").limit(20)
  end

  private


  def article_params
    params.require(:article).permit(:title, :image, :text, :category).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def page_article
    @articles = Article.includes(:user).page(params[:page]).per(6).order("created_at DESC")
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, only: [:create]

  def create
    @comment = Comment.create(text: comment_params[:text], article_id: comment_params[:article_id], user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to article_path(params[:article_id]) }
      format.json
    end
  end

  private

  def comment_params
    params.permit(:text, :article_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_article

  def create
    @like = Like.create(user_id: current_user.id, article_id: @article.id)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, article_id: @article.id)
    @like.destroy
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end

end

app/controllers/mylikes_controller.rb
class MylikesController < ApplicationController

  def show
    @likes = Like.select(:user_id, :article_id).distinct.where(user_id: current_user.id).page(params[:page]).per(6).order("created_at DESC")
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  before_action :user_decision, only: [:index]

  def index 
  end
  

  private

  def user_decision
    if user_signed_in?
      redirect_to articles_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @articles = user.articles.page(params[:page]).per(8).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mylikes_helper.rb
module MylikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/beauty.html.erb
<%= render partial: 'shared/f-header'%>

<%= render partial: 'shared/f-intro'%>

<%= render partial: 'shared/f-category'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Articles
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/beauty-card' %>
  <%= paginate(@articles) %>
</div>

app/views/articles/clean.html.erb
<%= render partial: 'shared/f-header'%>

<%= render partial: 'shared/f-intro'%>

<%= render partial: 'shared/f-category'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Articles
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/clean-card' %>
  <%= paginate(@articles) %>
</div>

app/views/articles/cook.html.erb
<%= render partial: 'shared/f-header'%>

<%= render partial: 'shared/f-intro'%>

<%= render partial: 'shared/f-category'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Articles
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/cook-card' %>
  <%= paginate(@articles) %>
</div>

app/views/articles/destroy.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'return'>
  <div class = 'return__message'>
    <span>投稿記事を削除しました</div>
  </div>
  <div class = 'return__btn'>
    <%= link_to 'トップページに戻る', articles_path %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'postbox'>
  <div class = 'postbox__card'>
  <%= form_with model: @article, local: true, method: :patch do |f| %>
    <div class = 'label'>
      <h3>写真</h3>
      <p>必須</p>
    </div>
    <%= f.label '画像を選択', for: 'postimage' %>
      <%= f.file_field :image, id: 'postimage', accept: 'image/*', class: 'hidden' %>
    <div class = "preview">
    </div>
    <div class = 'label'>
      <h3>タイトル</h3>
      <p>必須</p>
    </div>
    <%= f.text_field :title, placeholder: '記事のタイトル', class: 'post-input' %>
    <div class = 'label'>
      <h3>本文</h3>
      <p>必須</p>
    </div>
    <%= f.text_area :text, placeholder: 'ライフハック術の説明&#13;&#10;(例)&#13;&#10;手順1 まずは〜〜します。&#13;&#10;手順2 次に〜〜をします。&#13;&#10;最後をすれば〜〜です！！'.html_safe, cols: '50', rows: '5' %>
    <div class = 'label'>
      <h3>カテゴリ</h3>
       <p>必須</p>
    </div>
    <%= f.select :category, Article.categories.keys, {prompt: '---'} %>
    <%= f.submit :send, value: '投稿する', class: 'send' %>
  <% end %>
</div>

app/views/articles/index.html.erb
<%= render partial: 'shared/f-header'%>

<%= render partial: 'shared/f-intro'%>

<%= render partial: 'shared/f-category'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Articles
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/f-card' %>
  <%= paginate(@articles) %>
</div>



<style>/*
<div class = 'header'>
  <%= render partial: 'shared/header'%>
</div>

<div class = 'contents'>
  <div class = 'filters'>
    <ul class = 'filters__category'>
      <li><%= link_to 'All', articles_path %></li>
      <li><%= link_to 'Cook', cook_articles_path %></li>
      <li><%= link_to 'Clean', clean_articles_path %></li>
      <li><%= link_to 'Beauty', beauty_articles_path %></li>
      <li><%= link_to 'Other', other_articles_path %></li>
      <li><%= link_to 'Ranking', rank_articles_path %></li>
    </ul>
  </div>

  <div class = 'arrival'>
    <span class = 'arrival__text'>新着記事</span>
    <%= render partial: 'shared/card' %>
    <%= paginate(@articles) %>
  </div>
</div>
*/</style>

app/views/articles/new.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'postbox'>
  <div class = 'postbox__card'>
  <%= form_with model: @article, local: true do |f| %>
    <div class = 'label'>
      <h3>写真</h3>
      <p>必須</p>
    </div>
    <%= f.label '画像を選択', for: 'postimage' %>
      <%= f.file_field :image, id: 'postimage', accept: 'image/*', class: 'hidden' %>
    <div class = "preview">
    </div>
    <div class = 'label'>
      <h3>タイトル</h3>
      <p>必須</p>
    </div>
    <%= f.text_field :title, placeholder: '記事のタイトル', class: 'post-input' %>
    <div class = 'label'>
      <h3>本文</h3>
      <p>必須</p>
    </div>
    <%= f.text_area :text, placeholder: 'ライフハック術の説明&#13;&#10;(例)&#13;&#10;手順1 まずは〜〜します。&#13;&#10;手順2 次に〜〜をします。&#13;&#10;最後をすれば〜〜です！！'.html_safe, cols: '80', rows: '8' %>
    <div class = 'label'>
      <h3>カテゴリ</h3>
       <p>必須</p>
    </div>
    <%= f.select :category, Article.categories.keys, {prompt: '---'} %>
    <%= f.submit :send, value: '投稿する', class: 'send' %>
  <% end %>
</div>

app/views/articles/other.html.erb
<%= render partial: 'shared/f-header'%>

<%= render partial: 'shared/f-intro'%>

<%= render partial: 'shared/f-category'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Articles
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/other-card' %>
  <%= paginate(@articles) %>
</div>

app/views/articles/rank.html.erb
<%= render partial: 'shared/f-header'%>

<%= render partial: 'shared/f-intro'%>

<%= render partial: 'shared/f-category'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Popular
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/f-card' %>
  <%= paginate(@articles) %>
</div>

app/views/articles/search.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'f-index'>
  <span class = 'f-index__title'>
    Results
  </span>
</div>

<div class = 'f-contents'>
  <%= render partial: 'shared/f-card' %>
</div>

app/views/articles/show.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'main'>

  <div class = 'main__title'>
    <%= simple_format(@article.title) %>
  </div>

  
  <% if user_signed_in? && current_user.id == @article.user_id %>
    <ul class = 'gnav'>
      <li><a href=''><i class="fas fa-chevron-down"></i></a>
        <ul>
          <li><%= link_to 'この記事を削除する', "/articles/#{@article.id}", method: :delete %></li>
          <li><%= link_to 'この記事を編集する', edit_article_path, method: :get %></li>
        </ul>
      </li>
    </ul>
  <% end %>

  <div class = 'main__image'>
    <div class = 'main__image__box'>
      <%= image_tag @article.image.url, class: 'main__image__box--pic'%>
    </div>
  </div>

  <div class = 'main__text'>
    <%= simple_format(@article.text) %>
  </div>

  <hr>

  <% if current_user %>
    <div class = 'main__form'>
      <%= form_tag("/articles/#{@article.id}/comments", method: :post, id: "new_comment") do %>
        <textarea name="text" placeholder="ライフハック術を実践した感想などを描いてください" class = 'comment-form'></textarea>
        <input type="submit" value="コメントする" class = 'comment-send'>
      <% end %>
    </div>
  <% end %>

<% if user_signed_in? %>
  <% unless @article.user_id == current_user.id%>
    <div  class = 'main__like' id = "like-<%= @article.id %>">
      <%= render partial: 'shared/like' , locals: { article: @article } %>
    </div>
  <% end %>
<% end %>


  <div class = 'main__index'>
    <span>コメント一覧</span>
  </div>

  <% if @comments %>
    <% @comments.each do |comment| %>
      <div class = 'main__comment'>
        <div class = 'main__comment__user'>
          <div class = 'main__comment__user__name'>
            <span><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %><span>
          </div>
          <div class = 'main__comment__user__image'>
          </div>
          <div class = 'main__comment__user__text'>
            <span><%= comment.text %></span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %> 


</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}" ) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lifehacksharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alata&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ropa+Sans&display=swap" rel="stylesheet">

    <!-- drawer.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css">
    <!-- jquery & iScroll -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"></script>
    <!-- drawer.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$("#like-<%= @article.id %>").html("<%= j(render partial: 'shared/like', locals: { article: @article }) %>");

app/views/likes/destroy.js.erb
$("#like-<%= @article.id %>").html("<%= j(render partial: 'shared/like', locals: { article: @article }) %>");

app/views/mylikes/show.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'block'>
  <div class = 'block__user'>
    <div class = 'block__user__image'>
      <i class="fas fa-user"></i>
    </div>
    <div class = 'block__user__name'>
      <span><%= current_user.nickname %></span>
    </div>
  </div>

  <ul class = 'block__choice'>
    <li><%= link_to '投稿した記事一覧', user_path %></li>
    <li><%= link_to 'いいねした記事一覧', mylike_path %></li>
  </ul>

  <div class = 'f-contents'>
    <%= render partial: 'shared/like-card' %>
  </div>
</div>

app/views/shared/_beauty-card.html.erb
<% @articles.category_Beauty.each do |article| %>
  <a href='/articles/<%= article.id %>'>
    <div class = 'f-cards'>
      <%= image_tag article.image.url, class: 'f-cards__img' %>
        <div class = 'f-cards__img__box'>
          <p class = 'f-cards__img__box__title'><%= article.title %></p>
          <div class = 'f-cards__img__box__count'>
          <i class="far fa-heart" id = 'f-heart'></i>
          <% if article.likes_count.present? %>
            <span><%= article.likes_count %></span>
          <% else %>
            <span>0</span>
          <% end%>
          <i class="far fa-comment-dots" id = 'f-comment'></i>
          <% if article.comments.length.present? %>
            <span><%= article.comments.length %></span>
          <% else %>
            <span>0</span>
          <% end %>
          </div>
        </div>
    </div>
  </a>
<% end %>


<style>/*
<% @articles.category_Beauty.each do |article| %>
  <section class='card'>
    <a href='/articles/<%= article.id %>'>
      <%= image_tag article.image.url, class: 'card__img' %>
      <div class='card__content'>
        <h1 class='card__text'>
          <%= article.title %>
        </h1>
      </div>
      <div class = 'card__likes'>
        <i class='fas fa-heart'></i>
        <% if article.likes_count.present? %>
          <p><%= article.likes_count %></p>
        <% else %>
          <p>0</p>
        <% end %>
      </div>
    </a>
  </section>
<% end %>
*/</style>

app/views/shared/_card.html.erb
<% @articles.each do |article| %>
  <section class='card'>
    <a href='/articles/<%= article.id %>'>
      <%= image_tag article.image.url, class: 'card__img' %>
      <div class='card__content'>
        <h1 class='card__text'>
          <%= article.title %>
        </h1>
      </div>
      <div class = 'card__likes'>
        <i class='fas fa-heart'></i>
        <% if article.likes_count.present? %>
          <p><%= article.likes_count %></p>
        <% else %>
          <p>0</p>
        <% end %>
      </div>
    </a>
  </section>
<% end %>

app/views/shared/_clean-card.html.erb
<% @articles.category_Clean.each do |article| %>
  <a href='/articles/<%= article.id %>'>
    <div class = 'f-cards'>
      <%= image_tag article.image.url, class: 'f-cards__img' %>
        <div class = 'f-cards__img__box'>
          <p class = 'f-cards__img__box__title'><%= article.title %></p>
          <div class = 'f-cards__img__box__count'>
          <i class="far fa-heart" id = 'f-heart'></i>
          <% if article.likes_count.present? %>
            <span><%= article.likes_count %></span>
          <% else %>
            <span>0</span>
          <% end%>
          <i class="far fa-comment-dots" id = 'f-comment'></i>
          <% if article.comments.length.present? %>
            <span><%= article.comments.length %></span>
          <% else %>
            <span>0</span>
          <% end %>
          </div>
        </div>
    </div>
  </a>
<% end %>


<style>/*
<% @articles.category_Clean.each do |article| %>
  <section class='card'>
    <a href='/articles/<%= article.id %>'>
      <%= image_tag article.image.url, class: 'card__img' %>
      <div class='card__content'>
        <h1 class='card__text'>
          <%= article.title %>
        </h1>
      </div>
      <div class = 'card__likes'>
        <i class='fas fa-heart'></i>
        <% if article.likes_count.present? %>
          <p><%= article.likes_count %></p>
        <% else %>
          <p>0</p>
        <% end %>
      </div>
    </a>
  </section>
<% end %>
*/</style>

app/views/shared/_cook-card.html.erb
<% @articles.category_Cook.each do |article| %>
  <a href='/articles/<%= article.id %>'>
    <div class = 'f-cards'>
      <%= image_tag article.image.url, class: 'f-cards__img' %>
        <div class = 'f-cards__img__box'>
          <p class = 'f-cards__img__box__title'><%= article.title %></p>
          <div class = 'f-cards__img__box__count'>
          <i class="far fa-heart" id = 'f-heart'></i>
          <% if article.likes_count.present? %>
            <span><%= article.likes_count %></span>
          <% else %>
            <span>0</span>
          <% end%>
          <i class="far fa-comment-dots" id = 'f-comment'></i>
          <% if article.comments.length.present? %>
            <span><%= article.comments.length %></span>
          <% else %>
            <span>0</span>
          <% end %>
          </div>
        </div>
    </div>
  </a>
<% end %>


<style>/*
<% @articles.category_Cook.each do |article| %>
  <section class='card'>
    <a href='/articles/<%= article.id %>'>
      <%= image_tag article.image.url, class: 'card__img' %>
      <div class='card__content'>
        <h1 class='card__text'>
          <%= article.title %>
        </h1>
      </div>
      <div class = 'card__likes'>
        <i class='fas fa-heart'></i>
        <% if article.likes_count.present? %>
          <p><%= article.likes_count %></p>
        <% else %>
          <p>0</p>
        <% end %>
      </div>
    </a>
  </section>
<% end %>
*/</style>

app/views/shared/_f-card.html.erb
<% @articles.each do |article| %>
  <a href='/articles/<%= article.id %>'>
    <div class = 'f-cards'>
      <%= image_tag article.image.url, class: 'f-cards__img' %>
        <div class = 'f-cards__img__box'>
          <p class = 'f-cards__img__box__title'><%= article.title %></p>
          <div class = 'f-cards__img__box__count'>
          <i class="far fa-heart" id = 'f-heart'></i>
          <% if article.likes_count.present? %>
            <span><%= article.likes_count %></span>
          <% else %>
            <span>0</span>
          <% end%>
          <i class="far fa-comment-dots" id = 'f-comment'></i>
          <% if article.comments.length.present? %>
            <span><%= article.comments.length %></span>
          <% else %>
            <span>0</span>
          <% end %>
          </div>
        </div>
    </div>
  </a>
<% end %>

app/views/shared/_f-category.html.erb
<div class = 'f-filters'>
  <ul class = 'f-filters__category'>
    <li><%= link_to 'All', articles_path %></li>
    <li><%= link_to 'Cook', cook_articles_path %></li>
    <li><%= link_to 'Clean', clean_articles_path %></li>
    <li><%= link_to 'Beauty', beauty_articles_path %></li>
    <li><%= link_to 'Other', other_articles_path %></li>
    <li><%= link_to 'Ranking', rank_articles_path %></li>
  </ul>
</div>

app/views/shared/_f-header.html.erb
<div class = 'f-header'>
  <div class = 'f-header__contents'>
    <%= link_to 'LHS', articles_path %>
  </div>

  <body class="drawer drawer--left">
    <header role="banner">
      <button type="button" class="drawer-toggle drawer-hamburger" id = 'f-hamburger'>
        <span class="sr-only">toggle navigation</span>
        <span class="drawer-hamburger-icon"></span>
      </button>
      <nav class="drawer-nav" role="navigation">
        <ul class="drawer-menu">
          <% if user_signed_in? %>
            <li><a href='' class= 'drawer-brand'><%= current_user.nickname %>さん</a></li>
            <li><%= link_to 'トップへ', articles_path, class: "drawer-menu-item"%></li>
            <li><%= link_to '投稿する', new_article_path, class: "drawer-menu-item"%></li>
            <li><%= link_to 'マイページ', user_path(current_user), class: "drawer-menu-item" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'drawer-menu-item'%></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: 'drawer-menu-item' %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: 'drawer-menu-item'%></li>
          <% end %>
        </ul>
      </nav>
    </header>
  </body>

  <%= form_tag('/articles/search', method: :get) do %>
    <input type = "search" id= 'search-field'>
    <button title="search" type="submit" id='search-btn'>
      <i class="fa fa-search"></i>
    </button>
  <% end %>
</div>

app/views/shared/_f-intro.html.erb
<div class = 'f-image'>
  <div class = 'f-image__one'>
    <span class = 'f-image__one--text'>あなたのアイデアで</span>
  </div>
  <div class = 'f-image__two'>
    <span class = 'f-image__two--text'>暮らしを便利に。</span>
  </div>
</div>

app/views/shared/_header.html.erb
<div class = 'header__contents'>
  <%= link_to 'LHS', articles_path %>
</div>
<div class = 'header__search'>
  <%= form_tag('/articles/search', method: :get) do %>
    <input type = 'text' id = 'search-field' placeholder = 'キーワードを入力'/>
    <button title="search" type="submit" id='search-btn'>検索</button>
  <% end %>
</div>
<% if user_signed_in? %>
<ul class = 'menu'>
  <li><a href=''><%= current_user.nickname %>さん</a>
    <ul>
      <li><%= link_to '投稿する', new_article_path %></li>
      <li><%= link_to 'マイページ', user_path(current_user) %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'post'%></li>
    </ul>
  </li>
</ul>
<% else %>
<ul class = 'menu'>
  <li><i class='fas fa-align-justify'></i>
    <ul>
      <li><%= link_to 'ログイン', new_user_session_path, class: 'post' %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: 'post'%></li>
    </ul>
  </li>
</ul>
<% end %>

app/views/shared/_like.html.erb
<% if Like.find_by(user_id: current_user.id, article_id: article.id) %>
  <%= link_to "/articles/#{article.id}/likes", method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to "/articles/#{article.id}/likes", method: :post, remote: true do %>
    <i class="far fa-heart"></i>
    <% end %>
<% end %>

app/views/users/show.html.erb
<%= render partial: 'shared/f-header'%>

<div class = 'block'>
  <div class = 'block__user'>
    <div class = 'block__user__image'>
      <i class="fas fa-user"></i>
    </div>
    <div class = 'block__user__name'>
      <span><%= current_user.nickname %></span>
    </div>
  </div>

  <ul class = 'block__choice'>
    <li><%= link_to '投稿した記事一覧', user_path %></li>
    <li><%= link_to 'いいねした記事一覧', mylike_path %></li>
  </ul>

  <div class = 'f-contents'>
    <%= render partial: 'shared/f-card' %>
    <%= paginate(@articles) %>
  </div>
</div>